src = ["src"]


line-length=120

[lint]
select = [
    "B",    # flake8-bugbear
    "E",    # pycodestyle
    "F",    # Pyflakes
    "SIM",  # flake8-simplify
    "UP",   # pyupgrade
    "W292", # newline at end of file
    "N",    # PEP8 naming
    "D",    # pydocstyle
    "ANN",  # annotation
    "BLE",  # blind-except
    "A",    # flake8-builtins
    "ICN",  # import-convention
    "T20",  # print statement
    "G",    # logging format
    "Q",    # flake8-quotes
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
    "ARG",  # flake8-unused-arguments
    "FIX",  # flake8-fixme
    "ERA",  # flake8-eradicate
    "PERF", # perflint
    "E501", # line to long
]

ignore = [
    "ANN101", # missing type annotation for self in method
    "FIX002",
    "D100",
    "D401",
    "D417",
    "D104",
    "D203",
    "D213",
    "D401"
]

exclude = [
    "scripts/**",
    "src/driving/gamepad/driving_controller.py",
    "tests/**/test_data.py",
]

# Ignore unused imports in __init__.py files (would need __all__ otherwise)
[lint.per-file-ignores]
"__init__.py" = ["F401"]


[format]
quote-style = "double"
docstring-code-line-length = 80
