camera_ids:
  left: 0
  center: 0
  right: 0

image_manipulation:
  white_threshold: 220

lane_assist:
  line_detection:
    thresholds:
      zebra_crossing: 25000
    filtering:
        rel_height: 0.98
