camera_ids:
  left: 0
  center: 0
  right: 0


speed_modes:
  selected: ${.options.slow}
  options:
    slow: 25
    normal: 50
    fast: 75
    very_fast: 100

image_manipulation:
  gamma:
    adjust: false
    left: 1.0
    center: 1.0
    right: 1.0

  white_threshold: 185

lane_assist:
  line_detection:
    line_width: 50
    pixels_in_window: 1

    thresholds:
      zebra_crossing: 20_000
      line: 1_000

  line_following:
    requested_lane: 0
    initial_speed: 15

