object_detection:
  verbose: true

image_manipulation:
  white_threshold: 220

lane_assist:
  line_detection:
    thresholds:
      zebra_crossing: 25000
    filtering:
        rel_height: 0.98

telemetry:
  enabled: true
