camera_ids:
  left: 2
  center: 4
  right: 0

speed_modes:
  selected: ${.options.slow}
  options:
    slow: 20
    normal: 40
    fast: 60
    very_fast: 80

object_detection:
  verbose: true

image_manipulation:
  white_threshold: 200

lane_assist:
  line_detection:
    line_width: 50
    pixels_in_window: 1
    thresholds:
      zebra_crossing: 25000
      line: 1000
