camera_ids:
  left: 0
  center: 0
  right: 0

calibration:
  aruco_dict: 1  # DICT_4X4_100
  board_height: 8
  board_width: 10
  calibration_file: "${.save_dir}/latest.npz"
  max_image_height: 400
  max_image_width: 200
  marker_length: 0.086
  render_distance:
    front: 12.0
    side: 5.0
  save_dir: "../data/calibration"
  square_length: 0.115
  vanishing_line_offset: 0.02

speed_modes:
  selected: ${.options.slow}
  options:
    slow: 20
    normal: 40
    fast: 60
    very_fast: 80

image_manipulation:
  gamma:
    enabled: true
    left: 0.62
    center: 1.0
    right: 0.62
  white_threshold: 180

lane_assist:
  line_detection:
    pixels_in_window: 1
    window_margin_growth: 0.25

    window_sizing:
      height: 0.2
      width: 0.5

    thresholds:
      zebra_crossing: 20000

    filtering:
      active: true
      rel_height: 0.9

    pid:
      kp: 1
      ki: 0.1
      kd: 0.05

  line_following:
    requested_lane: 0
    initial_speed: 5

object_detection:
  model_path: "../models/yolo8s.pt"
  min_confidence: 0.6
  verbose: false
  image_size: 1280

speed_limit:
  height_ratio: 3.1
  min_distance: 3
  class_to_speed:
    5: 5
    6: 10
    7: 15
    8: 20
    9: 30
    10: 40

traffic_light:
  min_distance: 2

overtake:
  consecutive_frames: 3
  min_distance: 6
  min_angle: 250
  max_angle: 300
  range_threshold: 3000

crosswalk:
  overlap_margin: 0.2
  safe_zone_margin: 0.1
  min_distance: 3

telemetry:
  enabled: true
  server:
    port: 8000
    host: 0.0.0.0
    root_url: 192.168.1.89

braking:
  margin: 1.0
  max_force: 50
  min_force: 30

dynamic_speed:
  friction_coefficient: 0.9
  static: false
  static_speed: 10

lidar:
  port_name: "COM4"
  min_distance: 500
  max_distance_between_points: 1000
