# Kart
kart:
  max_steering_angle: 20

  speed_modes:
    selected: ${.options.slow}
    options:
      slow: 10
      normal: 20
      fast: 30
      very_fast: 40

  braking:
    margin: 1.0
    max_force: 50
    min_force: 30

camera_ids:
  left: 0
  center: 0
  right: 0

# Camera Calibration
calibration:
  aruco_dict: 1  # DICT_4X4_100
  board_height: 8
  board_width: 10
  calibration_file: "${.save_dir}/latest.npz"
  max_image_height: 400
  max_image_width: 200
  marker_length: 0.086
  render_distance:
    front: 12.0
    side: 5.0
  save_dir: "./data/calibration"
  square_length: 0.115
  vanishing_line_offset: 0.02

# Lane Assist
preprocessing:
  gamma:
    enabled: true
    left: 0.62
    center: 1.0
    right: 0.62
  white_threshold: 180

line_detection:
  pixels_in_window: 3
  window_margin_growth: 0  # percentage

  window_sizing:
    height: 0.5  # meters
    width: 0.5  # meters

  thresholds:
    max_angle_difference: 45  # degrees
    zebra_crossing: 1.0  # meters

  filtering:
    active: true
    rel_height: 0.9  # percentage
    min_distance: 1.0  # meters
    margin: 0.05  # meters

line_following:
  requested_lane: 0
  initial_speed: 5  # km/h

  max_steering_range: 40  # degrees
  look_ahead_distance: .5  # meters

  pid:
    kp: 40.0
    ki: 1.0
    kd: 0.5

# Object Detection
object_detection:
  model_path: "./models/yolo8s.pt"
  min_confidence: 0.6
  verbose: false
  image_size: 1280

speed_limit:
  height_ratio: 3.1
  min_distance: 3
  class_to_speed:
    6: 5
    7: 10
    8: 15
    9: 20

traffic_light:
  min_distance: 2

overtake:
  consecutive_frames: 3
  min_distance: 6
  min_angle: 230
  max_angle: 280
  range_threshold: 3000

parking:
  min_distance: 1

crosswalk:
  overlap_margin: 0.2
  safe_zone_margin: 0.1
  min_distance: 3

# Other
telemetry:
  enabled: true
  server:
    port: 8000
    host: 0.0.0.0
    root_url: 192.168.1.89

dynamic_speed:
  friction_coefficient: 0.3
  static: false
  static_speed: 10

lidar:
  port_name: "/dev/ttyUSB0"
  min_distance: 500
  max_distance_between_points: 1000
