kart:
  lidar_offset: 1.6
  max_steering_angle: 20

  dimensions:
    length: 3.2
    width: 1.4

  braking:
    max_force: 100
    min_force: 0

  speed_modes:
    selected: 20

line_following:
  requested_lane:
    override: true
    lane: 0

  pid:
    kp: 20.0
    ki: 1.0
    kd: 0.5

preprocessing:
  white_threshold: 174

dynamic_speed:
  friction_coefficient: 0.5
  static: false
  static_speed: 40
