name: Ruff
on:
  push:
    branches:
    - master
    
  pull_request:
    branches:
    - master
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with: 
          src: "./src"
          args: --config .ruff.toml --fix --unsafe-fixes ./src

      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: 'style fixes by ruff'