name: Ruff
on:
  push:
  pull_request:
    branches:
    - master
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with: 
          src: "./src"
          args: check --config .ruff.toml ./src
