name: Ruff
on:
  # only run when ruff relevant files are changed.
  # or when it it is a pull request to master
  push:
    paths:
      - '**.py'
      - '.ruff.toml'
      - '.github/workflows/ruff.yml'
  pull_request:
    branches:
    - master
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with: 
          src: "./src"
          args: check --config .ruff.toml ./src
