name: Unit tests

on:
  push:
    paths:
      - 'requirements.txt'
      - '.github/workflows/testing.yml'
      - 'src/**'
      - 'tests/**'
      -
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: [3.10.12]

    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgl1-mesa-glx
          version: 1.0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # cahce python using venv
      - uses: actions/cache@v2
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt

#    set pythonpath without using set-env
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}/src" >> $GITHUB_ENV

      - name: Run tests
        run: python -m pytest tests
